import getViews from '../pages/index';
export default [
    {
        path:'/',
        title:"首页",
        redirect:"/home/index"
    },
    {
        path:"/login",
        title:"登录",
        component:getViews('Login')
    },
    {
        path:"/registry",
        title:"注册",
        component:getViews('Registry')
    },
    {
        path:"/changePassword",
        title:"忘记密码",
        component:getViews('ChangePassword')
    },
    {
        path:"/createVote",
        title:"创建投票",
        component:getViews('CreateVote')
    },
    {
        path:"/voteList",
        title:"投票列表",
        component:getViews('VoteList')
    },
    {
        path:"/home",
        title:"首页",
        component:getViews('Home'),
        children:[
            {
                path:"/home/index",
                component:getViews('Home/Index'),
                title:"首页"
            },
            {
                path:"/home/my",
                component:getViews('Home/My'),
                title:"我的"
            }
        ]
    },
]